flowchart TD
    p0((Channel.fromPath))
    p1([splitCsv])
    p2([map])
    p3[QUALITY_CHECK_WF:FASTQC]
    p4([collect])
    p5[QUALITY_CHECK_WF:MULTIQC]
    p6(( ))
    p7[QUALITY_CHECK_WF:QUANTTB_QUANT]
    p8(( ))
    p9[QUALITY_CHECK_WF:UTILS_QUANTTB_SAMPLE_QC]
    p10(( ))
    p11([collect])
    p12[QUALITY_CHECK_WF:UTILS_QUANTTB_COHORT_STATS]
    p13([splitCsv])
    p14([map])
    p15([join])
    p16(( ))
    p17(( ))
    p18[MAP_WF:BWA_MEM]
    p19([map])
    p20([groupTuple])
    p21[CALL_WF:SAMTOOLS_MERGE]
    p22[CALL_WF:GATK_MARK_DUPLICATES]
    p23(( ))
    p24(( ))
    p25(( ))
    p26(( ))
    p27[CALL_WF:GATK_BASE_RECALIBRATOR]
    p28(( ))
    p29(( ))
    p30[CALL_WF:GATK_APPLY_BQSR]
    p31[CALL_WF:SAMTOOLS_INDEX]
    p32(( ))
    p33(( ))
    p34[CALL_WF:GATK_HAPLOTYPE_CALLER]
    p35(( ))
    p36(( ))
    p37(( ))
    p38[CALL_WF:GATK_HAPLOTYPE_CALLER__MINOR_VARIANTS]
    p39(( ))
    p40(( ))
    p41(( ))
    p42(( ))
    p43[CALL_WF:LOFREQ_CALL__NTM]
    p44(( ))
    p45[CALL_WF:LOFREQ_INDELQUAL]
    p46[CALL_WF:SAMTOOLS_INDEX__LOFREQ]
    p47(( ))
    p48(( ))
    p49[CALL_WF:LOFREQ_CALL]
    p50(( ))
    p51[CALL_WF:LOFREQ_FILTER]
    p52(( ))
    p53(( ))
    p54[CALL_WF:DELLY_CALL]
    p55[CALL_WF:BCFTOOLS_VIEW]
    p56(( ))
    p57[CALL_WF:GATK_INDEX_FEATURE_FILE]
    p58(( ))
    p59(( ))
    p60[CALL_WF:SAMTOOLS_STATS]
    p61(( ))
    p62[CALL_WF:GATK_COLLECT_WGS_METRICS]
    p63(( ))
    p64(( ))
    p65[CALL_WF:GATK_FLAG_STAT]
    p66([join])
    p67([join])
    p68([join])
    p69[CALL_WF:UTILS_SAMPLE_STATS]
    p70([collect])
    p71[CALL_WF:UTILS_COHORT_STATS]
    p72([collect])
    p73([flatten])
    p74([collate])
    p75([splitCsv])
    p76([map])
    p77([filter])
    p78([map])
    p79([join])
    p80([flatten])
    p81([filter])
    p82([collect])
    p83([flatten])
    p84([filter])
    p85([map])
    p86([reduce])
    p87(( ))
    p88(( ))
    p89(( ))
    p90(( ))
    p91[MERGE_WF:PREPARE_COHORT_VCF:GATK_COMBINE_GVCFS]
    p92(( ))
    p93(( ))
    p94[MERGE_WF:PREPARE_COHORT_VCF:GATK_GENOTYPE_GVCFS]
    p95(( ))
    p96[MERGE_WF:PREPARE_COHORT_VCF:SNPEFF]
    p97[MERGE_WF:PREPARE_COHORT_VCF:BGZIP]
    p98(( ))
    p99[MERGE_WF:PREPARE_COHORT_VCF:GATK_INDEX_FEATURE_FILE__COHORT]
    p100(( ))
    p101(( ))
    p102(( ))
    p103(( ))
    p104(( ))
    p105(( ))
    p106(( ))
    p107[MERGE_WF:SNP_ANALYSIS:GATK_SELECT_VARIANTS__SNP]
    p108((Channel.of))
    p109([ifEmpty])
    p110([map])
    p111([flatten])
    p112([filter])
    p113([reduce])
    p114([ifEmpty])
    p115([filter])
    p116([filter])
    p117([collect])
    p118([ifEmpty])
    p119([filter])
    p120([filter])
    p121([collect])
    p122([ifEmpty])
    p123(( ))
    p124(( ))
    p125(( ))
    p126(( ))
    p127[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:GATK_VARIANT_RECALIBRATOR__ANN7]
    p128(( ))
    p129(( ))
    p130(( ))
    p131([join])
    p132(( ))
    p133[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:UTILS_ELIMINATE_ANNOTATION__ANN7]
    p134([map])
    p135(( ))
    p136(( ))
    p137(( ))
    p138[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:GATK_VARIANT_RECALIBRATOR__ANN6]
    p139(( ))
    p140(( ))
    p141(( ))
    p142([join])
    p143(( ))
    p144[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:UTILS_ELIMINATE_ANNOTATION__ANN6]
    p145([map])
    p146(( ))
    p147(( ))
    p148(( ))
    p149[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:GATK_VARIANT_RECALIBRATOR__ANN5]
    p150(( ))
    p151(( ))
    p152(( ))
    p153([join])
    p154(( ))
    p155[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:UTILS_ELIMINATE_ANNOTATION__ANN5]
    p156([map])
    p157(( ))
    p158(( ))
    p159(( ))
    p160[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:GATK_VARIANT_RECALIBRATOR__ANN4]
    p161(( ))
    p162(( ))
    p163(( ))
    p164([join])
    p165(( ))
    p166[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:UTILS_ELIMINATE_ANNOTATION__ANN4]
    p167([map])
    p168(( ))
    p169(( ))
    p170(( ))
    p171[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:GATK_VARIANT_RECALIBRATOR__ANN3]
    p172(( ))
    p173(( ))
    p174(( ))
    p175([join])
    p176(( ))
    p177[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:UTILS_ELIMINATE_ANNOTATION__ANN3]
    p178([map])
    p179(( ))
    p180(( ))
    p181(( ))
    p182[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:GATK_VARIANT_RECALIBRATOR__ANN2]
    p183(( ))
    p184(( ))
    p185(( ))
    p186([join])
    p187(( ))
    p188[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:UTILS_ELIMINATE_ANNOTATION__ANN2]
    p189(( ))
    p190([join])
    p191([join])
    p192([join])
    p193([join])
    p194([join])
    p195([flatten])
    p196([filter])
    p197([collect])
    p198([join])
    p199([join])
    p200([join])
    p201([join])
    p202([join])
    p203([flatten])
    p204([filter])
    p205([collect])
    p206([join])
    p207([join])
    p208([join])
    p209([join])
    p210([join])
    p211([flatten])
    p212([filter])
    p213([collect])
    p214(( ))
    p215[MERGE_WF:SNP_ANALYSIS:OPTIMIZE_VARIANT_RECALIBRATION:UTILS_SELECT_BEST_ANNOTATIONS]
    p216(( ))
    p217([join])
    p218([join])
    p219(( ))
    p220(( ))
    p221(( ))
    p222[MERGE_WF:SNP_ANALYSIS:GATK_APPLY_VQSR__SNP]
    p223(( ))
    p224(( ))
    p225(( ))
    p226(( ))
    p227[MERGE_WF:SNP_ANALYSIS:GATK_SELECT_VARIANTS__EXCLUSION__SNP]
    p228(( ))
    p229(( ))
    p230(( ))
    p231(( ))
    p232(( ))
    p233(( ))
    p234(( ))
    p235[MERGE_WF:INDEL_ANALYSIS:GATK_SELECT_VARIANTS__INDEL]
    p236([join])
    p237[MERGE_WF:GATK_MERGE_VCFS__INC]
    p238(( ))
    p239[MERGE_WF:RESISTANCE_ANALYSIS:TBPROFILER_VCF_PROFILE__COHORT]
    p240(( ))
    p241(( ))
    p242[MERGE_WF:RESISTANCE_ANALYSIS:TBPROFILER_COLLATE__COHORT]
    p243(( ))
    p244[MERGE_WF:RESISTANCE_ANALYSIS:BGZIP]
    p245(( ))
    p246[MERGE_WF:RESISTANCE_ANALYSIS:TBPROFILER_VCF_PROFILE__LOFREQ]
    p247(( ))
    p248([collect])
    p249(( ))
    p250(( ))
    p251[MERGE_WF:RESISTANCE_ANALYSIS:TBPROFILER_COLLATE__LOFREQ]
    p252(( ))
    p253((Channel.of))
    p254([ifEmpty])
    p255([flatten])
    p256((Channel.of))
    p257([filter])
    p258([reduce])
    p259([filter])
    p260([collect])
    p261([ifEmpty])
    p262([filter])
    p263([collect])
    p264([ifEmpty])
    p265(( ))
    p266(( ))
    p267(( ))
    p268[MERGE_WF:PHYLOGENY_ANALYSIS__INCCOMPLEX:GATK_SELECT_VARIANTS__PHYLOGENY]
    p269[MERGE_WF:PHYLOGENY_ANALYSIS__INCCOMPLEX:GATK_VARIANTS_TO_TABLE]
    p270[MERGE_WF:PHYLOGENY_ANALYSIS__INCCOMPLEX:SNPSITES]
    p271[MERGE_WF:PHYLOGENY_ANALYSIS__INCCOMPLEX:SNPDISTS]
    p272(( ))
    p273[MERGE_WF:PHYLOGENY_ANALYSIS__INCCOMPLEX:IQTREE]
    p274(( ))
    p275(( ))
    p276(( ))
    p277(( ))
    p278(( ))
    p279(( ))
    p280(( ))
    p281([join])
    p282(( ))
    p283[MERGE_WF:CLUSTER_ANALYSIS__INCCOMPLEX:CLUSTERPICKER__5SNP]
    p284(( ))
    p285(( ))
    p286[MERGE_WF:CLUSTER_ANALYSIS__INCCOMPLEX:CLUSTERPICKER__12SNP]
    p287(( ))
    p288((Channel.of))
    p289([ifEmpty])
    p290([flatten])
    p291((Channel.of))
    p292([filter])
    p293([reduce])
    p294([filter])
    p295([collect])
    p296([ifEmpty])
    p297([filter])
    p298([collect])
    p299([ifEmpty])
    p300(( ))
    p301(( ))
    p302(( ))
    p303[MERGE_WF:PHYLOGENY_ANALYSIS__EXCOMPLEX:GATK_SELECT_VARIANTS__PHYLOGENY]
    p304[MERGE_WF:PHYLOGENY_ANALYSIS__EXCOMPLEX:GATK_VARIANTS_TO_TABLE]
    p305[MERGE_WF:PHYLOGENY_ANALYSIS__EXCOMPLEX:SNPSITES]
    p306[MERGE_WF:PHYLOGENY_ANALYSIS__EXCOMPLEX:SNPDISTS]
    p307(( ))
    p308[MERGE_WF:PHYLOGENY_ANALYSIS__EXCOMPLEX:IQTREE]
    p309(( ))
    p310(( ))
    p311(( ))
    p312(( ))
    p313(( ))
    p314(( ))
    p315(( ))
    p316([join])
    p317(( ))
    p318[MERGE_WF:CLUSTER_ANALYSIS__EXCOMPLEX:CLUSTERPICKER__5SNP]
    p319(( ))
    p320(( ))
    p321[MERGE_WF:CLUSTER_ANALYSIS__EXCOMPLEX:CLUSTERPICKER__12SNP]
    p322(( ))
    p0 --> p1
    p1 --> p2
    p2 -->|reads_ch| p3
    p3 --> p4
    p4 --> p5
    p5 --> p6
    p2 -->|reads_ch| p7
    p7 --> p9
    p7 --> p9
    p8 -->|relabundanceThreshold| p9
    p9 --> p11
    p9 --> p10
    p11 --> p12
    p12 --> p13
    p13 --> p14
    p14 --> p15
    p2 -->|reads_ch| p15
    p15 -->|reads_ch| p18
    p16 -->|reference| p18
    p17 -->|*| p18
    p18 -->|bam_sorted_reads_ch| p19
    p19 --> p20
    p20 -->|normalize_libraries_ch| p21
    p21 --> p22
    p22 --> p27
    p22 --> p23
    p24 -->|dbsnp| p27
    p25 -->|ref_fasta| p27
    p26 -->|*| p27
    p27 --> p30
    p28 -->|ref_fasta| p30
    p29 -->|*| p30
    p30 --> p31
    p31 --> p34
    p32 -->|ref_fasta| p34
    p33 -->|*| p34
    p34 --> p72
    p34 --> p35
    p31 --> p38
    p36 -->|reference| p38
    p37 -->|*| p38
    p38 --> p40
    p38 --> p39
    p31 --> p43
    p41 -->|reference| p43
    p42 -->|*| p43
    p43 --> p68
    p30 --> p45
    p44 -->|ref_fasta| p45
    p45 --> p46
    p46 --> p49
    p47 -->|ref_fasta| p49
    p48 -->|*| p49
    p49 -->|lofreq_vcf_ch| p51
    p50 -->|ref_fasta| p51
    p51 --> p52
    p31 --> p54
    p53 -->|reference| p54
    p54 --> p55
    p55 --> p57
    p56 -->|outputPrefix| p57
    p57 --> p58
    p30 --> p60
    p59 -->|reference| p60
    p60 --> p66
    p30 --> p62
    p61 -->|reference| p62
    p62 --> p66
    p30 --> p65
    p63 -->|ref_fasta| p65
    p64 -->|*| p65
    p65 --> p67
    p66 --> p67
    p67 --> p68
    p68 -->|sample_stats_ch| p69
    p69 --> p70
    p70 --> p71
    p71 --> p75
    p72 -->|gvcf_ch| p73
    p73 --> p74
    p74 -->|collated_gvcfs_ch| p79
    p75 --> p76
    p76 --> p77
    p77 --> p78
    p78 -->|sample_stats_ch| p79
    p79 --> p80
    p80 --> p81
    p81 -->|selected_gvcfs_ch| p82
    p82 -->|cohort_gvcfs_ch| p83
    p83 --> p84
    p84 --> p85
    p85 --> p86
    p86 -->|gvcfs_string_ch| p91
    p87 -->|joint_name| p91
    p82 -->|cohort_gvcfs_ch| p91
    p88 -->|ref_fasta| p91
    p89 -->|ref_exit_rif_gvcf| p91
    p90 -->|*| p91
    p91 --> p94
    p92 -->|ref_fasta| p94
    p93 -->|*| p94
    p94 --> p96
    p95 -->|ref_fasta| p96
    p96 --> p97
    p97 --> p99
    p98 -->|outputPrefix| p99
    p99 -->|cohort_vcf_and_index_ch| p107
    p100 -->|variantType| p107
    p101 -->|prefix| p107
    p102 -->|resourceFilesArg| p107
    p103 -->|resourceFiles| p107
    p104 -->|resourceFileIndexes| p107
    p105 -->|reference| p107
    p106 -->|*| p107
    p107 -->|select_variants_vcftuple_ch| p127
    p108 --> p109
    p109 --> p110
    p110 --> p111
    p111 -->|arg_files_ch| p112
    p112 --> p113
    p113 --> p114
    p114 -->|args_ch| p127
    p111 -->|arg_files_ch| p115
    p115 --> p116
    p116 --> p117
    p117 --> p118
    p118 -->|resources_files_ch| p127
    p111 -->|arg_files_ch| p119
    p119 --> p120
    p120 --> p121
    p121 --> p122
    p122 -->|resources_file_indexes_ch| p127
    p123 -->|analysisMode| p127
    p124 -->|annotations| p127
    p125 -->|reference| p127
    p126 -->|*| p127
    p127 --> p190
    p127 --> p131
    p127 --> p130
    p127 --> p129
    p127 --> p128
    p127 --> p131
    p131 -->|elim_ann7_ch| p133
    p132 -->|analysisType| p133
    p133 --> p134
    p133 --> p206
    p134 -->|ann6_ch| p138
    p135 -->|analysisMode| p138
    p107 -->|select_variants_vcftuple_ch| p138
    p114 -->|args_ch| p138
    p118 -->|resources_files_ch| p138
    p122 -->|resources_file_indexes_ch| p138
    p136 -->|reference| p138
    p137 -->|*| p138
    p138 --> p190
    p138 --> p142
    p138 --> p141
    p138 --> p140
    p138 --> p139
    p138 --> p142
    p142 -->|elim_ann6_ch| p144
    p143 -->|analysisType| p144
    p144 --> p145
    p144 --> p206
    p145 -->|ann5_ch| p149
    p146 -->|analysisMode| p149
    p107 -->|select_variants_vcftuple_ch| p149
    p114 -->|args_ch| p149
    p118 -->|resources_files_ch| p149
    p122 -->|resources_file_indexes_ch| p149
    p147 -->|reference| p149
    p148 -->|*| p149
    p149 --> p191
    p149 --> p153
    p149 --> p152
    p149 --> p151
    p149 --> p150
    p149 --> p153
    p153 -->|elim_ann5_ch| p155
    p154 -->|analysisType| p155
    p155 --> p156
    p155 --> p207
    p156 -->|ann4_ch| p160
    p157 -->|analysisMode| p160
    p107 -->|select_variants_vcftuple_ch| p160
    p114 -->|args_ch| p160
    p118 -->|resources_files_ch| p160
    p122 -->|resources_file_indexes_ch| p160
    p158 -->|reference| p160
    p159 -->|*| p160
    p160 --> p192
    p160 --> p164
    p160 --> p163
    p160 --> p162
    p160 --> p161
    p160 --> p164
    p164 -->|elim_ann4_ch| p166
    p165 -->|analysisType| p166
    p166 --> p167
    p166 --> p208
    p167 -->|ann3_ch| p171
    p168 -->|analysisMode| p171
    p107 -->|select_variants_vcftuple_ch| p171
    p114 -->|args_ch| p171
    p118 -->|resources_files_ch| p171
    p122 -->|resources_file_indexes_ch| p171
    p169 -->|reference| p171
    p170 -->|*| p171
    p171 --> p193
    p171 --> p175
    p171 --> p174
    p171 --> p173
    p171 --> p172
    p171 --> p175
    p175 -->|elim_ann3_ch| p177
    p176 -->|analysisType| p177
    p177 --> p178
    p177 --> p209
    p178 -->|ann2_ch| p182
    p179 -->|analysisMode| p182
    p107 -->|select_variants_vcftuple_ch| p182
    p114 -->|args_ch| p182
    p118 -->|resources_files_ch| p182
    p122 -->|resources_file_indexes_ch| p182
    p180 -->|reference| p182
    p181 -->|*| p182
    p182 --> p194
    p182 --> p186
    p182 --> p185
    p182 --> p184
    p182 --> p183
    p182 --> p186
    p186 -->|elim_ann2_ch| p188
    p187 -->|analysisType| p188
    p188 --> p189
    p188 --> p210
    p190 --> p191
    p191 --> p192
    p192 --> p193
    p193 --> p194
    p194 --> p195
    p195 --> p196
    p196 --> p197
    p197 -->|recal_vcf_files_ch| p215
    p127 --> p198
    p138 --> p198
    p198 --> p199
    p149 --> p199
    p199 --> p200
    p160 --> p200
    p200 --> p201
    p171 --> p201
    p201 --> p202
    p182 --> p202
    p202 --> p203
    p203 --> p204
    p204 --> p205
    p205 -->|tranches_files_ch| p215
    p206 --> p207
    p207 --> p208
    p208 --> p209
    p209 --> p210
    p210 --> p211
    p211 --> p212
    p212 --> p213
    p213 -->|annotations_and_tranches_json_files_ch| p215
    p214 -->|joint_name| p215
    p215 --> p217
    p215 --> p218
    p215 --> p216
    p107 -->|select_variants_vcftuple_ch| p217
    p217 --> p218
    p218 -->|vqsr_ch| p222
    p219 -->|analysisMode| p222
    p220 -->|reference| p222
    p221 -->|*| p222
    p222 -->|snp_inc_vcf_ch| p227
    p223 -->|analysisMode| p227
    p224 -->|intervalFile| p227
    p225 -->|reference| p227
    p226 -->|*| p227
    p227 -->|vcf_ch| p268
    p228 -->|variantType| p235
    p229 -->|prefix| p235
    p99 -->|cohort_vcf_and_index_ch| p235
    p230 -->|resourceFilesArg| p235
    p231 -->|resourceFiles| p235
    p232 -->|resourceFileIndexes| p235
    p233 -->|reference| p235
    p234 -->|*| p235
    p235 -->|indel_vcf_ch| p236
    p222 -->|snp_inc_vcf_ch| p236
    p236 -->|merge_inc_vcf_ch| p237
    p237 -->|merged_vcf_ch| p239
    p238 -->|resistanceDb| p239
    p239 --> p242
    p240 -->|joint_name| p242
    p241 -->|resistanceDb| p242
    p242 --> p243
    p49 -->|lofreq_vcf_ch| p244
    p244 --> p246
    p245 -->|resistanceDb| p246
    p246 --> p247
    p246 --> p248
    p248 --> p251
    p249 -->|joint_name| p251
    p250 -->|resistanceDb| p251
    p251 --> p252
    p253 --> p254
    p254 --> p255
    p255 -->|arg_files_ch| p257
    p256 -->|prefix| p268
    p257 --> p258
    p258 -->|args_ch| p268
    p255 -->|arg_files_ch| p259
    p259 --> p260
    p260 --> p261
    p261 -->|resources_files_ch| p268
    p255 -->|arg_files_ch| p262
    p262 --> p263
    p263 --> p264
    p264 -->|resources_file_indexes_ch| p268
    p265 -->|variantType| p268
    p266 -->|reference| p268
    p267 -->|*| p268
    p268 --> p269
    p256 -->|prefix| p269
    p269 --> p270
    p256 -->|prefix| p270
    p270 --> p271
    p256 -->|prefix| p271
    p271 --> p272
    p256 -->|prefix| p273
    p270 --> p273
    p273 --> p281
    p273 --> p280
    p273 --> p279
    p273 --> p278
    p273 --> p277
    p273 --> p276
    p273 --> p275
    p273 --> p274
    p270 --> p281
    p281 -->|cluster_files_ch| p283
    p282 -->|snpCount| p283
    p256 -->|prefix| p283
    p283 --> p284
    p281 -->|cluster_files_ch| p286
    p285 -->|snpCount| p286
    p256 -->|prefix| p286
    p286 --> p287
    p288 --> p289
    p289 --> p290
    p290 -->|arg_files_ch| p292
    p291 -->|prefix| p303
    p292 --> p293
    p293 -->|args_ch| p303
    p290 -->|arg_files_ch| p294
    p294 --> p295
    p295 --> p296
    p296 -->|resources_files_ch| p303
    p290 -->|arg_files_ch| p297
    p297 --> p298
    p298 --> p299
    p299 -->|resources_file_indexes_ch| p303
    p300 -->|variantType| p303
    p227 -->|vcf_ch| p303
    p301 -->|reference| p303
    p302 -->|*| p303
    p303 --> p304
    p291 -->|prefix| p304
    p304 --> p305
    p291 -->|prefix| p305
    p305 --> p306
    p291 -->|prefix| p306
    p306 --> p307
    p291 -->|prefix| p308
    p305 --> p308
    p308 --> p316
    p308 --> p315
    p308 --> p314
    p308 --> p313
    p308 --> p312
    p308 --> p311
    p308 --> p310
    p308 --> p309
    p305 --> p316
    p316 -->|cluster_files_ch| p318
    p317 -->|snpCount| p318
    p291 -->|prefix| p318
    p318 --> p319
    p316 -->|cluster_files_ch| p321
    p320 -->|snpCount| p321
    p291 -->|prefix| p321
    p321 --> p322
