# Replace these values to reflect your samplesheet and file-paths
# FIXME: Use absolute paths
#
# Samplesheets

input_samplesheet: "/home/xbs-nf-runs/data/EarlyMGIT.10samples.slurm.csv"

# Main output dir

outdir :  "/home/xbs-nf-results-earlymgit10samples"

# Location for manually created conda-envs

conda_envs_location :  "/home/xbs-nf-conda_envs"

# Some boolean options
optimize_variant_recalibration :  false
compute_minor_variants :  true
dataset_is_not_contaminated :  true
only_validate_fastqs :  false
