project:
  type: website

website:
  title: "MAGMA"

  sidebar:
      style: "docked"
      search: true
      contents:
        - text: "Usage"
          href: usage.qmd
        - text: "Output"
          href: output.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

